# Configuration OpenAI
openai.api.key= Nathanaêl key-Api
# Configuration Spring Boot
server.port=8080
spring.application.name=hazavao-app

# Logging
logging.level.com.examen.prog=DEBUG
logging.level.org.springframework.web=DEBUG